name: List Deployments on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  list-deployments:
    runs-on: ubuntu-latest
    outputs:
      environment_urls: ${{ steps.determine_merged_branch.outputs.environment_urls }}
    steps:
      - name: Determine merged branch
        id: determine_merged_branch
        run: |
          BRANCH_FROM_PR=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments?ref=${BRANCH_FROM_PR}")
          DEPLOYMENTS_URLS=$(echo "$DEPLOYMENTS" | jq -r '.[].statuses_url')
          environment_urls=()
          for url in $DEPLOYMENTS_URLS; do
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$url")
            environment_url=$(echo "$response" | jq -r '.[] | .environment_url')
            environment_urls+=("$environment_url")
          done
          echo "environment_urls=${environment_urls[@]}" >> $GITHUB_OUTPUT

  echo-environment-urls:
    runs-on: ubuntu-latest
    needs: list-deployments
    steps:
      - name: Get environment URLs from previous job
        run: |
          echo "Environment URLs: ${{ needs.list-deployments.outputs.environment_urls }}"

      - name: Iterate over environment URLs
        run: |
          read -r -a urls <<< "${{ needs.list-deployments.outputs.environment_urls }}"
          for url in "${urls[@]}"; do
            echo "Environment URL: $url"
          done