name: List Deployments on PR Close

on:
  pull_request:
    types: [closed]

jobs:
  list-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Determine merged branch
        id: determine_merged_branch
        run: |
          MERGED_BRANCH=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          BRANCH_FROM_PR=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")
          if [ "$BRANCH_FROM_PR" != "null" ]; then
            MERGED_BRANCH=$BRANCH_FROM_PR
          fi
          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments?ref=${MERGED_BRANCH}")
          DEPLOYMENTS_URLS=$(echo "$DEPLOYMENTS" | jq -r '.[].statuses_url')
          echo "$DEPLOYMENTS_URLS"
