name: Test

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: https://test.com
    steps:
      - name: Log Deployment URL
        run: echo test deployment
