name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  SHA_SHORT: "https://test.com/${{ github.sha }}"

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ env.SHA_SHORT }}
    steps:
      - name: Log Deployment URL
        run: echo test deployment ${{ env.SHA_SHORT }}
