name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.set_url.outputs.url }}
    steps:
      - name: Set URL
        id: set_url
        run: |
          echo "https://test.com/$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Log Deployment URL
        run: echo test deployment
